// @ts-check

/**
 * @typedef {"single_select" | "multi_select" | "text" | "number" | "photo" | "summary"} QuestionType
 * @typedef {"result" | "location" | "target" | "tackle" | "conditions" | "photo" | "memo" | "next" | "confirm"} QuestionSection
 */

export const QUESTION_SECTION_LABELS = {
  result: "結果",
  location: "場所",
  target: "理由",
  tackle: "道具",
  conditions: "条件",
  photo: "写真",
  memo: "メモ",
  next: "次回",
  confirm: "確認",
};

export const QUESTION_MODE_SECTIONS = {
  quick: ["result", "location", "target", "tackle", "photo", "memo", "next", "confirm"],
  detailed: ["result", "location", "conditions", "tackle", "photo", "memo", "next", "confirm"],
  photo_first: ["photo", "memo", "confirm"],
};

export const QUESTION_DEFINITIONS = {
  quick: [
    {
      id: "quick_result",
      section: "result",
      title: "今日の結果は？",
      description: "まずは近いものを選んでください",
      type: "single_select",
      required: true,
      allowSkip: false,
      allowDefer: false,
    },
    {
      id: "quick_location",
      section: "location",
      title: "場所は？",
      description: "前回や最近の場所から選べます",
      type: "single_select",
      required: false,
      allowSkip: false,
      allowDefer: true,
    },
    {
      id: "quick_reason",
      section: "target",
      title: "反応なしの理由は？",
      description: "反応なしの日も、次の釣行のヒントになります",
      type: "single_select",
      required: false,
      allowSkip: false,
      allowDefer: true,
      options: [
        { label: "潮が動いていなかった", value: "reason_0" },
        { label: "風が強かった", value: "reason_1" },
        { label: "ベイトが見えなかった", value: "reason_2" },
        { label: "人が多かった", value: "reason_3" },
        { label: "時間帯が合わなかった", value: "reason_4" },
        { label: "分からない", value: "reason_5" },
        { label: "自由に書く", value: "manual" },
      ],
      visibleWhen: (draft) => draft.trip.result?.result_type === "no_response",
    },
    {
      id: "quick_tackle",
      section: "tackle",
      title: "使ったものは？",
      description: "前回や最近の道具から選べます",
      type: "single_select",
      required: false,
      allowSkip: false,
      allowDefer: true,
    },
    {
      id: "quick_photo",
      section: "photo",
      title: "写真は追加しますか？",
      description: "その場で残しておくと あとで見返しやすくなります",
      type: "photo",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
    {
      id: "quick_memo",
      section: "memo",
      title: "ひとことメモ",
      description: "短いメモだけでも残せます",
      type: "text",
      required: false,
      allowSkip: true,
      allowDefer: false,
    },
    {
      id: "quick_next",
      section: "next",
      title: "次回試すことは？",
      description: "思いついたことだけ短く残せます",
      type: "text",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
  ],
  detailed: [
    {
      id: "detailed_result",
      section: "result",
      title: "結果",
      description: "まずは結果と釣果を整理します",
      type: "summary",
      required: true,
      allowSkip: false,
      allowDefer: false,
    },
    {
      id: "detailed_location",
      section: "location",
      title: "場所",
      description: "場所、水域、釣行種別を記録します",
      type: "summary",
      required: true,
      allowSkip: false,
      allowDefer: false,
    },
    {
      id: "detailed_conditions",
      section: "conditions",
      title: "条件",
      description: "天候、風、潮や濁りを残します",
      type: "summary",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
    {
      id: "detailed_tackle",
      section: "tackle",
      title: "釣法・ルアー/餌",
      description: "使ったものをまとめて入力します",
      type: "summary",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
    {
      id: "detailed_photo",
      section: "photo",
      title: "写真",
      description: "必要な写真だけ追加します",
      type: "photo",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
    {
      id: "detailed_memo",
      section: "memo",
      title: "メモ",
      description: "その日のまとめや反省点を残します",
      type: "summary",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
    {
      id: "detailed_next",
      section: "next",
      title: "次回試すこと",
      description: "最後に、次回の一手を残します",
      type: "text",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
  ],
  photo_first: [
    {
      id: "photo_first_photo",
      section: "photo",
      title: "写真だけ先に残しますか？",
      description: "日時は自動で入ります写真はあとから説明を追記できます",
      type: "photo",
      required: true,
      allowSkip: false,
      allowDefer: false,
    },
    {
      id: "photo_first_memo",
      section: "memo",
      title: "写真のひとことメモ",
      description: "場所や状況を短く残しておくと、あとで追記しやすくなります",
      type: "text",
      required: false,
      allowSkip: true,
      allowDefer: true,
    },
  ],
};
